# Do not deploy this file on server, it is only for local development

services:
  app:
    command: uvicorn src.main.web:app --host 0.0.0.0 --port ${APP_BACKEND_PORT} --reload

    volumes:
      - .:/app
      - /app/.venv
  nginx:
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
