"""add event logs table

Revision ID: f704e41d6bd8
Revises: 0d3b55881302
Create Date: 2026-09-15 16:03:49.275947

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f704e41d6bd8"
down_revision: str | Sequence[str] | None = "0d3b55881302"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("USER", "NOTE", name="objecttype").create(op.get_bind())
    sa.Enum("USER", "SYSTEM", "ANONYMOUS", name="actortype").create(op.get_bind())
    op.create_table(
        "event_logs",
        sa.Column(
            "actor_type",
            postgresql.ENUM(
                "USER",
                "SYSTEM",
                "ANONYMOUS",
                name="actortype",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column(
            "object_type",
            postgresql.ENUM("USER", "NOTE", name="objecttype", create_type=False),
            nullable=True,
        ),
        sa.Column("object_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_logs")),
    )
    op.create_index(
        "ix_event_logs_actor",
        "event_logs",
        [
            "actor_type",
            "actor_id",
            sa.literal_column("created_at DESC NULLS LAST"),
            sa.literal_column("id DESC"),
        ],
        unique=False,
    )
    op.create_index(
        "ix_event_logs_created_at",
        "event_logs",
        [
            sa.literal_column("created_at DESC NULLS LAST"),
            sa.literal_column("id DESC"),
        ],
        unique=False,
    )
    op.create_index(
        "ix_event_logs_event_type",
        "event_logs",
        [
            "event_type",
            sa.literal_column("created_at DESC NULLS LAST"),
            sa.literal_column("id DESC"),
        ],
        unique=False,
    )
    op.create_index(
        "ix_event_logs_object",
        "event_logs",
        [
            "object_type",
            "object_id",
            sa.literal_column("created_at DESC NULLS LAST"),
            sa.literal_column("id DESC"),
        ],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_event_logs_object", table_name="event_logs")
    op.drop_index("ix_event_logs_event_type", table_name="event_logs")
    op.drop_index("ix_event_logs_created_at", table_name="event_logs")
    op.drop_index("ix_event_logs_actor", table_name="event_logs")
    op.drop_table("event_logs")
    sa.Enum("USER", "SYSTEM", "ANONYMOUS", name="actortype").drop(op.get_bind())
    sa.Enum("USER", "NOTE", name="objecttype").drop(op.get_bind())
    # ### end Alembic commands ###
