"""add outbox messages table

Revision ID: cc5c196b9abe
Revises: 0aaeae15442c
Create Date: 2026-08-13 07:05:27.944077

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cc5c196b9abe"
down_revision: str | None = "0aaeae15442c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("PENDING", "PUBLISHED", "FAILED", name="outboxmessagestatus").create(
        op.get_bind()
    )
    op.create_table(
        "outbox_messages",
        sa.Column("task_name", sa.String(length=255), nullable=False),
        sa.Column("args", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("kwargs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING",
                "PUBLISHED",
                "FAILED",
                name="outboxmessagestatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_messages")),
    )
    op.create_index(
        "ix_outbox_messages_pending_created_at",
        "outbox_messages",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_outbox_messages_pending_created_at",
        table_name="outbox_messages",
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.drop_table("outbox_messages")
    sa.Enum("PENDING", "PUBLISHED", "FAILED", name="outboxmessagestatus").drop(
        op.get_bind()
    )
    # ### end Alembic commands ###
