"""Parity guard for Alembic autogenerate discovery.

`migrations/env.py` imports the `models` package to populate `Base.metadata`.
A model module missing from `models/__init__.py` therefore yields an EMPTY
autogenerated migration with no error anywhere. This test finds every
`src/**/models.py` that defines mapped models and fails unless
`models/__init__.py` imports it explicitly.

The check is static (AST of `models/__init__.py`) on purpose: under pytest the
whole application is already imported through conftest fixtures, so
`Base.metadata` is fully populated regardless of what the `models` package
imports and cannot serve as the evidence.
"""

from __future__ import annotations

import ast
import importlib
import inspect
from pathlib import Path

from src.core.database.base import Base

REPO_ROOT = Path(__file__).resolve().parents[2]
MODELS_INIT = REPO_ROOT / "models" / "__init__.py"


def _modules_imported_by_models_package() -> set[str]:
    # Only unconditional module-level imports count: an import inside
    # `if TYPE_CHECKING:`, a function body or any other branch is not
    # guaranteed to run when Alembic imports the package.
    tree = ast.parse(MODELS_INIT.read_text())
    imported: set[str] = set()
    for node in tree.body:
        if isinstance(node, ast.ImportFrom) and node.module:
            imported.add(node.module)
        elif isinstance(node, ast.Import):
            imported.update(alias.name for alias in node.names)
    return imported


def _defines_mapped_models(module_name: str) -> bool:
    module = importlib.import_module(module_name)
    return any(
        issubclass(obj, Base) and obj is not Base and obj.__module__ == module_name
        for _, obj in inspect.getmembers(module, inspect.isclass)
    )


def test_every_model_module_is_registered_in_models_package() -> None:
    imported = _modules_imported_by_models_package()
    offenders = [
        module_name
        for path in sorted((REPO_ROOT / "src").rglob("models.py"))
        if (module_name := ".".join(path.relative_to(REPO_ROOT).with_suffix("").parts))
        not in imported
        and _defines_mapped_models(module_name)
    ]
    assert not offenders, (
        "Model modules not imported by models/__init__.py - Alembic autogenerate "
        f"silently produces an EMPTY migration for their tables: {offenders}"
    )
